### ISSUE TITLE
`'datetime' is not defined` in `env.py`

### ISSUE THREAD

**Issue by danjampro** [Caltech-IPAC/firefly_client#47]
Hello,

I have come across a bug that seems to exist in the latest version of `firefly_client`. In particular, there is an undefined reference to `datetime.datetime` in `env.py`:

https://github.com/Caltech-IPAC/firefly_client/blob/41b0157d77edd1852e2f3d5aecc39f4f661ba3a5/firefly_client/env.py#L68

**Comment by robyww** [comment]
Yes, your right. Looks like a couple of problems with that line.

I will put out a patch build today.

**Comment by robyww** [comment]
https://github.com/Caltech-IPAC/firefly_client/pull/48

**Comment by robyww** [comment]
fixed in version 2.7.2

**Comment by jaladh-singhal** [comment]
Closing since already fixed!
